### ISSUE TITLE
更新到v0.2.1版本后设置页面无法打开

### ISSUE THREAD

**Issue by 111027866** [Lukoning/LyricBarBlur#1]
# #
![屏幕截图 2024-07-07 163256](https://github.com/Lukoning/LyricBarBlur/assets/120190945/246537d3-b462-4003-acf9-6358d8ca1646)
网易云版本2.10.13
betterncm版本1.3.3

**Comment by 111027866** [comment]
![屏幕截图 2024-07-07 164829](https://github.com/Lukoning/LyricBarBlur/assets/120190945/219293f3-791b-4c1a-b7d0-a8d23cb75a81)
v0.1.5版本可以正常使用

**Comment by Lukoning** [comment]
奇了怪了，网易云和BetterNCM版本相同，但在我的电脑上是能正常使用的
![image](https://github.com/Lukoning/LyricBarBlur/assets/92252063/263528b3-c932-4b2c-a565-3a96fa38c463)

**Comment by Lukoning** [comment]
稍等，我找到问题了

**Comment by Lukoning** [comment]
这个问题是v0.1.x与v0.2.x的配置不兼容造成的……没考虑到兼容性问题……
v0.2.2版本会修复这个问题

现在有个临时解决方法，但是会丢失设置：
更新插件至v0.2.1
重载后在网易云内按下F12
在上面选择Application选项卡
左侧找到Local Storage，展开
选择orpheus://orpheus
右边列表中找到LyricBarBlurSettings，右键Delete
重载/重启网易云

**Comment by 111027866** [comment]
![屏幕截图 2024-07-07 175357](https://github.com/Lukoning/LyricBarBlur/assets/120190945/bde0707b-87c9-4109-a8ea-cb307df5ba4d)
设置页面能进了但设置后不生效，应用，重载，重启网易云都试过了

**Comment by 111027866** [comment]
突然好了，能用就行不管了

**Comment by Lukoning** [comment]
> ![屏幕截图 2024-07-07 175357](https://private-user-images.githubusercontent.com/120190945/346325719-bde0707b-87c9-4109-a8ea-cb307df5ba4d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzNDY0MzQsIm5iZiI6MTcyMDM0NjEzNCwicGF0aCI6Ii8xMjAxOTA5NDUvMzQ2MzI1NzE5LWJkZTA3MDdiLTg3YzktNDEwOS1hOGVhLWNiMzA3ZGY1YmE0ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwN1QwOTU1MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NThjZmIxZGQ4NTcwZWI2ZTE4ZTY4MzU5YWYzZjAyMjdjNzZjYTk5YzUzMjFkM2M1Y2IzMzM4MjM4NTVkNzY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kfv6_ih8cNWVGBnS9m-EcxokygrVdApxKnmt53ijiGE) 设置页面能进了但设置后不生效，应用，重载，重启网易云都试过了

要不你再删一次？我没法复现这个问题

**Comment by Lukoning** [comment]
> 突然好了，能用就行不管了

OK 收到
