### ISSUE TITLE
v0.2.6 设置界面三个操作按钮错位显示异常

### ISSUE THREAD

**Issue by PigeonP** [Lukoning/LyricBarBlur#3]
如图，三个按钮不在同一行
![PixPin_2024-07-20_14-05-58](https://github.com/user-attachments/assets/aaf03424-bcf1-4e79-8694-cfddc33d03b9)
![PixPin_2024-07-20_14-06-24](https://github.com/user-attachments/assets/656c27ab-3172-4e58-8662-e77e9d5cb85e)

**Comment by PigeonP** [comment]
补充可能有用的信息：使用的网易云音乐版本号为 2.10.13（Build:202675)（Patch:1:12f60b8）

**Comment by Lukoning** [comment]
![image](https://github.com/user-attachments/assets/773d9816-b108-4270-8aba-e1f136e3d251)

没法复现

0.2.7版本改了这三个按钮的定位方式，应该能解决问题

**Comment by Lukoning** [comment]
我看到你好像改了字体，可能是这个的问题

**Comment by Lukoning** [comment]
新版本上架插件商店了，看下更新完了有没有解决问题

**Comment by PigeonP** [comment]
> 新版本上架插件商店了，看下更新完了有没有解决问题

已更新，问题解决了。
可能是我修改了字体的问题（用TinyNCM改的PingFang SC字体）
